modified README to add discord server
RedstoneQoL/mod pull request #14
Opened 2023-02-05 21:38 UTC by ItsEntDev

removes fabric example mod Setup header, and links development discord server

2023-02-05 21:40 UTC, Matthias1590 requested changes

2023-02-05 21:40 UTC, Matthias1590 commented on README.md
> +> Discord Server: https://discord.gg/wAu9k2fGyK
Could you make this a badge?

2023-02-06 08:13 UTC, ItsEntDev commented on README.md
> +> Discord Server: https://discord.gg/wAu9k2fGyK
Done, sorry for the long wait.

2023-02-06 14:29 UTC, Matthias1590 approved these changes

2023-02-06 14:29 UTC, merged