logo changed to use the new version by orbyfied#8316
RedstoneQoL/mod pull request #28
Opened 2023-02-09 18:35 UTC by ItsEntDev

2023-02-09 19:57 UTC, RUGMJ commented
The uri for the image should be in this repo and not your personal one

2023-02-09 19:58 UTC, ItsEntDev commented
> The uri for the image should be in this repo and not your personal one

I can't, because the image hasn't been pushed to this repo

2023-02-09 21:27 UTC, RUGMJ commented
But you can still link it? Relative linking instead of absolute would work just fine

2023-02-10 07:51 UTC, Matthias1590 requested changes

2023-02-10 07:51 UTC, Matthias1590 commented on README.md
> +![logo](https://raw.githubusercontent.com/ItsEntDev/RSTools/dev/rst_logo.png)
Please use a relative path to the image in the repo

2023-02-10 15:25 UTC, ItsEntDev commented on README.md
> +![logo](https://raw.githubusercontent.com/ItsEntDev/RSTools/dev/rst_logo.png)
done, even though I don't really see why it matters.

2023-02-10 16:17 UTC, RUGMJ commented on README.md
> +![logo](https://raw.githubusercontent.com/ItsEntDev/RSTools/dev/rst_logo.png)
> done, even though I don't really see why it matters.

It matters because if your account were ever hacked or if you for whatever reason wanted to, you would have the ability to change the logo to whatever you wanted to

2023-02-10 16:18 UTC, RUGMJ commented on README.md
> +![logo](https://raw.githubusercontent.com/ItsEntDev/RSTools/dev/rst_logo.png)
and it also makes much more sense for the image to be in the actual repo

2023-02-10 16:45 UTC, Matthias1590 approved these changes

2023-02-10 16:45 UTC, merged