Added BaseConvert Command
RedstoneQoL/mod pull request #36
Opened 2023-02-12 22:29 UTC by RUGMJ

2023-02-12 22:34 UTC, Matthias1590 requested changes
Add ArgumentType implementations for hexadecimal, decimal, binary and octal numbers, then add a command that takes a number and an optional output base that outputs the number to either the specified output base or all 4 bases (use an enum and an enum ArgumentType for this)

2023-02-13 18:17 UTC, RUGMJ commented
How would it know what the input base is?

2023-02-13 18:25 UTC, RUGMJ commented
The prefixes java use could be could, none for decimal, 0x for hex 0 for octal and 0b for binary

2023-02-14 18:58 UTC, Matthias1590 approved these changes

2023-02-14 18:58 UTC, merged