Added /glass command
RedstoneQoL/mod pull request #37
Opened 2023-02-13 17:19 UTC by MiranCZ

Added /glass command #34. Also added Utility for getting item by its name and for color codes which I used.

2023-02-13 17:45 UTC, Matthias1590 requested changes

2023-02-13 17:45 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/glass/GlassFeature.java
> +            client.player.sendMessage(Text.of(redPrefix + "You need to be in creative mode to execute this command!"), false);
This isn't really necessary, it's not a vanilla mod so we don't really care if we give survival players free glass and wool

2023-02-13 17:45 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/RedstoneToolsClient.java
> +        ItemUtils.register();
Don't have a register method for ItemUtils as it introduces temporal coupling and is not necessary

2023-02-13 17:45 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/utils/ColorCodeUtils.java
> +package com.domain.redstonetools.utils;
I don't think we need this class, its nice but it'll make it harder to stay consistent in reporting errors, plain text or throwing command syntax exceptions works fine

2023-02-13 17:45 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/utils/ItemUtils.java
> +    public static void register() {
Remove this method, make other methods search the registry instead of a map

2023-02-13 18:07 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/utils/ItemUtils.java
> +    public static void register() {
I thought it would be better to have one method than searching trough it every time. Register method instead of straight creation is becouse I was not sure if the array is loaded at that time. I will remove the ColorUtils class, and make the text just white

2023-02-13 18:08 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/utils/ColorCodeUtils.java
> +package com.domain.redstonetools.utils;
I will remove the ColorUtils class, and make the text just white

2023-02-13 18:08 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/features/commands/glass/GlassFeature.java
> +            client.player.sendMessage(Text.of(redPrefix + "You need to be in creative mode to execute this command!"), false);
ok

2023-02-14 07:42 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/utils/ItemUtils.java
> +    public static void register() {
I guess we could have a method that finds an item by name but it should return that item instead of an arbitrary integer

2023-02-14 11:08 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/utils/ItemUtils.java
> +    public static void register() {
So the method I have, but its map with Items not integers?

2023-02-14 12:19 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/utils/ItemUtils.java
> +    public static void register() {
Yes, you could still look up items by their names but it'll return an item instead of an int

2023-02-14 15:26 UTC, Matthias1590 approved these changes

2023-02-14 15:29 UTC, Matthias1590 commented
Please merge into dev

2023-02-14 15:46 UTC, MiranCZ commented
I cant. "Only those with write access to this repository can merge pull requests."

2023-02-14 16:50 UTC, Matthias1590 commented
Changing the destination branch is what I meant

2023-02-14 16:50 UTC, merged